[project]
name = "bettermorphology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "conllu>=6.0.0",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]
